version: '3.8'

services:
  app:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./uploads:/usr/src/app/uploads # Mount the uploads directory
    environment:
      - PORT=${PORT}
      - API_KEY=${API_KEY}
      - NODE_ENV=${NODE_ENV}