services:
  app: # Your Node.js application service
    build: .
    ports:
      - "80:8080" # Map host port 80 to container port 8080
                  # This means external requests to host:80 will go to app-container:8080
    volumes:
      - ./uploads:/usr/src/app/uploads
      - ./temp_uploads:/usr/src/app/temp_uploads # Ensure temp_uploads is also persistent/mounted
    environment:
      - PORT=8080 # Your app listens on 8080 inside the container
      - API_KEY=${API_KEY}
      - NODE_ENV=${NODE_ENV}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 3